### PR TITLE
Dynamic Time History Collection 

### LINKED ISSUE #1203: [Feature] Time History output including spatial coordinates
**What is the requested feature?**
For many analysis one may want to investigate 2D profiles of quantities of interest as a function of space coordinates, without requiring the entire mesh output in `vtk` or `silo` format. To enable this, Time History output `hdf5` files should include the spatial coordinates of each support point location, i.e. `elementCenter` for cell-centered quantities, `ReferencePosition` for vertex-centered quantities. 

Here's an example. Cell-centered pressure values are requested in output. The generated `hdf5` currently consists of two datasets: (i) `Time`, and (ii) `pressure` (screenshot below). The `Time` dataset contains the timestep values (here 9x1 values). The `pressure` dataset contains the pressure values at the selected cells (here 9x10 values, i.e. 10 cells and  9 timesteps). It would be extremely useful if the cell centers were always provided as an additional dataset (size 3x10). As such, the Time History output would become a self-contained piece of information.

On a side note, I was able to extract cell centers via a `SoloEvent`. However, they are given as a three dimensional with 2x10x3 values (screenshot below).

Screen Shot 2020-10-15 at 1 10 56 PM

Screen Shot 2020-10-15 at 1 11 10 PM

Screen Shot 2020-10-15 at 1 11 16 PM

Screen Shot 2020-10-15 at 1 50 04 PM

Screen Shot 2020-10-15 at 1 50 27 PM

Screen Shot 2020-10-15 at 1 50 38 PM

Screen Shot 2020-10-15 at 1 50 45 PM

Screen Shot 2020-10-15 at 1 50 51 PM

### LINKED ISSUE #1309: [Bug] Time history in parallel: abnormally slow setup and crash on exit
**Describe the bug**
I am facing some problems related to TimeHistory when I run Tutorials 4 and 5 in parallel:
- If I run these tutorials on one rank, everything works fine and I am able to generate hdf5 files for the well pressures.
- If I run these tutorials on multiple ranks, the function `TimeHistoryOutput::initCollectorParallel` is very slow (the simulator hangs for 2 minutes there) and the simulation ends with the following error message:
<details>
<summary>HDF5 error message with 8 ranks</summary>

```
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 292 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: ../../hdf5/src/H5Dint.c line 1384 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: ../../hdf5/src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../hdf5/src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../hdf5/src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: ../../hdf5/src/H5Gloc.c line 378 in H5G__loc_find_cb(): object 'Time' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 896 in H5Dset_extent(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 331 in H5Dclose(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../hdf5/src/H5Fint.c line 1652 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: ../../hdf5/src/H5Fsuper.c line 623 in H5F__super_read(): truncated file: eof = 6064, sblock->base_addr = 0, stored_eof = 6792
    major: File accessibilty
    minor: File has been truncated
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 282 in H5Dopen2(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: ../../hdf5/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 372 in H5Dget_space(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5Shyper.c line 7053 in H5Sselect_hyperslab(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5Dio.c line 314 in H5Dwrite(): dset_id is not a dataset ID
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5S.c line 489 in H5Sclose(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 331 in H5Dclose(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5F.c line 671 in H5Fclose(): not a file ID
    major: File accessibilty
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 292 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: ../../hdf5/src/H5Dint.c line 1384 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: ../../hdf5/src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../hdf5/src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../hdf5/src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: ../../hdf5/src/H5Gloc.c line 378 in H5G__loc_find_cb(): object 'Time' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 896 in H5Dset_extent(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 331 in H5Dclose(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 292 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: ../../hdf5/src/H5Dint.c line 1384 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: ../../hdf5/src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../hdf5/src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../hdf5/src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: ../../hdf5/src/H5Gloc.c line 378 in H5G__loc_find_cb(): object 'Time' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 896 in H5Dset_extent(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 331 in H5Dclose(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 292 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: ../../hdf5/src/H5Dint.c line 1384 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: ../../hdf5/src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../hdf5/src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../hdf5/src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: ../../hdf5/src/H5Gloc.c line 378 in H5G__loc_find_cb(): object 'Time' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 372 in H5Dget_space(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5Shyper.c line 7053 in H5Sselect_hyperslab(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5Dio.c line 314 in H5Dwrite(): dset_id is not a dataset ID
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5S.c line 489 in H5Sclose(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 331 in H5Dclose(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 292 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: ../../hdf5/src/H5Dint.c line 1384 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: ../../hdf5/src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../hdf5/src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../hdf5/src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: ../../hdf5/src/H5Gloc.c line 378 in H5G__loc_find_cb(): object 'Time' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 896 in H5Dset_extent(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 331 in H5Dclose(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 292 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: ../../hdf5/src/H5Dint.c line 1384 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: ../../hdf5/src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../hdf5/src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../hdf5/src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: ../../hdf5/src/H5Gloc.c line 378 in H5G__loc_find_cb(): object 'Time' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 896 in H5Dset_extent(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 331 in H5Dclose(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 292 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: ../../hdf5/src/H5Dint.c line 1384 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: ../../hdf5/src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../hdf5/src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../hdf5/src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: ../../hdf5/src/H5Gloc.c line 378 in H5G__loc_find_cb(): object 'Time' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 372 in H5Dget_space(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5Shyper.c line 7053 in H5Sselect_hyperslab(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5Dio.c line 314 in H5Dwrite(): dset_id is not a dataset ID
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5S.c line 489 in H5Sclose(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 331 in H5Dclose(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 292 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: ../../hdf5/src/H5Dint.c line 1384 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: ../../hdf5/src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../hdf5/src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../hdf5/src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: ../../hdf5/src/H5Gloc.c line 378 in H5G__loc_find_cb(): object 'Time' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 896 in H5Dset_extent(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 331 in H5Dclose(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
```
</details>

<details>
<summary>Here is the Caliper output on 1 rank for Tutorial 5: `TimeHistoryOutput::initCollectorParallel` takes 0.17 second</summary>

```
Path                                             Min time/rank Max time/rank Avg time/rank Time %    
main                                                  0.082372      0.082372      0.082372  0.058594 
  geosx::EventManager::run                            3.705249      3.705249      3.705249  2.635680 
    geosx::PackCollection::collect                    0.002719      0.002719      0.002719  0.001934 
    geosx::SolverBase::execute                        0.002499      0.002499      0.002499  0.001778 
      geosx::ReservoirSolverBase::solverStep          0.335712      0.335712      0.335712  0.238804 
        geosx::SolverBase::nonlinearImplicitStep      8.417916      8.417916      8.417916  5.987974 
          geosx::Composition~~eFlow::updateState      0.003832      0.003832      0.003832  0.002726 
            geosx::Compositio~~datePhaseMobility      0.016791      0.016791      0.016791  0.011944 
            geosx::Compositio~~pdateRelPermModel      0.012401      0.012401      0.012401  0.008821 
            geosx::Compositio~~:updateSolidModel      0.007014      0.007014      0.007014  0.004989 
            geosx::Compositio~~aseVolumeFraction      0.058852      0.058852      0.058852  0.041864 
            geosx::Compositio~~:updateFluidModel     46.144092     46.144092     46.144092 32.823993 
            geosx::Compositio~~ComponentFraction      0.007942      0.007942      0.007942  0.005649 
          geosx::Communicati~~:synchronizeUnpack      0.000811      0.000811      0.000811  0.000577 
          geosx::Communicati~~ronizePackSendRecv      0.011266      0.011266      0.011266  0.008014 
          geosx::Communicati~~ePackSendRecvSizes      0.004483      0.004483      0.004483  0.003189 
          geosx::Composition~~heckSystemSolution      0.140006      0.140006      0.140006  0.099591 
          geosx::Composition~~gForSystemSolution      0.147286      0.147286      0.147286  0.104770 
          geosx::Composition~~gForSystemSolution      0.021029      0.021029      0.021029  0.014959 
          geosx::ReservoirSo~~rBase::solveSystem      0.013819      0.013819      0.013819  0.009830 
            geosx::SolverBase::solveSystem           63.217419     63.217419     63.217419 44.968880 
          geosx::Composition~~culateResidualNorm      0.179631      0.179631      0.179631  0.127778 
          geosx::Composition~~BoundaryConditions      0.003189      0.003189      0.003189  0.002268 
            geosx::FieldSpeci~~ionManager::apply      0.001958      0.001958      0.001958  0.001393 
          geosx::Composition~~mPressureRelations      0.204964      0.204964      0.204964  0.145798 
          geosx::Composition~~VolumeBalanceTerms      0.057369      0.057369      0.057369  0.040809 
          geosx::Composition~~:assembleFluxTerms      0.075614      0.075614      0.075614  0.053787 
          geosx::Composition~~tePerforationRates      0.162383      0.162383      0.162383  0.115509 
          geosx::Composition~~haseVolumeFraction      0.129763      0.129763      0.129763  0.092305 
          geosx::Composition~~::updateFluidModel      0.759798      0.759798      0.759798  0.540472 
          geosx::Composition~~eComponentFraction      0.107829      0.107829      0.107829  0.076703 
          geosx::Composition~~ow::assembleSystem      0.003208      0.003208      0.003208  0.002282 
            geosx::Compositio~~olumeBalanceTerms      0.020703      0.020703      0.020703  0.014727 
            geosx::Compositio~~assembleFluxTerms      0.396314      0.396314      0.396314  0.281913 
            geosx::Compositio~~AccumulationTerms      0.084421      0.084421      0.084421  0.060052 
        geosx::Compositiona~~utePerforationRates      0.016734      0.016734      0.016734  0.011904 
        geosx::Compositiona~~PhaseVolumeFraction      0.012568      0.012568      0.012568  0.008940 
        geosx::Compositiona~~l::updateFluidModel      0.077999      0.077999      0.077999  0.055484 
        geosx::Compositiona~~teComponentFraction      0.011145      0.011145      0.011145  0.007928 
        geosx::Compositiona~~ll::initializeWells      0.011332      0.011332      0.011332  0.008061 
          geosx::Composition~~tePerforationRates      0.000726      0.000726      0.000726  0.000516 
          geosx::Composition~~haseVolumeFraction      0.000566      0.000566      0.000566  0.000403 
          geosx::Composition~~::updateFluidModel      0.001878      0.001878      0.001878  0.001336 
          geosx::Composition~~eComponentFraction      0.000647      0.000647      0.000647  0.000460 
        geosx::Compositiona~~seFlow::updateState      0.001121      0.001121      0.001121  0.000797 
          geosx::Composition~~pdatePhaseMobility      0.010093      0.010093      0.010093  0.007180 
          geosx::Composition~~updateRelPermModel      0.005270      0.005270      0.005270  0.003749 
          geosx::Composition~~::updateSolidModel      0.002276      0.002276      0.002276  0.001619 
          geosx::Composition~~haseVolumeFraction      0.018456      0.018456      0.018456  0.013128 
          geosx::Composition~~::updateFluidModel     10.707057     10.707057     10.707057  7.616324 
          geosx::Composition~~eComponentFraction      0.005416      0.005416      0.005416  0.003853 
        geosx::ReservoirSolverBase::setupSystem       2.645445      2.645445      2.645445  1.881803 
          geosx::Composition~~ingSparsityPattern      0.135487      0.135487      0.135487  0.096377 
          geosx::Communicati~~:synchronizeUnpack      0.000204      0.000204      0.000204  0.000145 
          geosx::Communicati~~ronizePackSendRecv      0.003489      0.003489      0.003489  0.002482 
          geosx::Communicati~~ePackSendRecvSizes      0.001350      0.001350      0.001350  0.000960 
    geosx::TimeHistoryOutput::execute                 0.490426      0.490426      0.490426  0.348858 
  geosx::ProblemManager::problemSetup                 0.542361      0.542361      0.542361  0.385801 
    geosx::CompositionalM~~onditionsPreSubGroups      0.003602      0.003602      0.003602  0.002562 
      geosx::Compositional~~initializeFluidState      0.000305      0.000305      0.000305  0.000217 
        geosx::Compositiona~~updatePhaseMobility      0.000185      0.000185      0.000185  0.000132 
        geosx::Compositiona~~:updateRelPermModel      0.000117      0.000117      0.000117  0.000083 
        geosx::Compositiona~~w::updateSolidModel      0.000080      0.000080      0.000080  0.000057 
        geosx::Compositiona~~PhaseVolumeFraction      0.000232      0.000232      0.000232  0.000165 
        geosx::Compositiona~~w::updateFluidModel      0.270722      0.270722      0.270722  0.192575 
      geosx::Communication~~s::synchronizeUnpack      0.000002      0.000002      0.000002  0.000001 
      geosx::Communication~~chronizePackSendRecv      0.000034      0.000034      0.000034  0.000024 
      geosx::Communication~~izePackSendRecvSizes      0.000018      0.000018      0.000018  0.000013 
    geosx::FluxApproximat~~onditionsPreSubGroups      0.052222      0.052222      0.052222  0.037147 
      geosx::FieldSpecificationManager::apply         0.000005      0.000005      0.000005  0.000004 
    geosx::TimeHistoryOut~~initCollectorParallel      0.176399      0.176399      0.176399  0.125479 
    geosx::FieldSpecificationManager::apply           0.004065      0.004065      0.004065  0.002892 
    geosx::ProblemManager::generateMesh               0.593801      0.593801      0.593801  0.422393 
      geosx::DomainPartiti~~:setupCommunications      0.000383      0.000383      0.000383  0.000272 
        geosx::FaceManager::sortAllFaceNodes          0.002634      0.002634      0.002634  0.001874 
        geosx::CommunicationTools::findGhosts         0.005186      0.005186      0.005186  0.003689 
          geosx::ObjectManag~~ase::fixUpDownMaps      0.000022      0.000022      0.000022  0.000016 
        geosx::Communicatio~~tionBoundaryObjects      0.000493      0.000493      0.000493  0.000351 
        geosx::Communicatio~~assignGlobalIndices      0.013432      0.013432      0.013432  0.009555 
          geosx::EdgeManager~~GlobalIndexNumbers      0.002500      0.002500      0.002500  0.001778 
          geosx::ObjectManag~~ctGlobalToLocalMap      0.017998      0.017998      0.017998  0.012803 
          geosx::FaceManager~~GlobalIndexNumbers      0.001795      0.001795      0.001795  0.001277 
      geosx::CellElementRe~~::generateAggregates      0.000006      0.000006      0.000006  0.000004 
      geosx::DomainPartition::generateSets            0.002813      0.002813      0.002813  0.002001 
      geosx::NodeManager::setEdgeMaps                 0.015484      0.015484      0.015484  0.011014 
      geosx::EdgeManager::buildEdges                  0.022352      0.022352      0.022352  0.015900 
        geosx::populateMaps                           0.011762      0.011762      0.011762  0.008367 
        geosx::resizeEdgeToFaceMap                    0.011771      0.011771      0.011771  0.008373 
        geosx::createEdgesByLowestNode                0.012906      0.012906      0.012906  0.009181 
      geosx::NodeManager::setFaceMaps                 0.017340      0.017340      0.017340  0.012335 
      geosx::FaceManager::buildFaces                  0.019868      0.019868      0.019868  0.014133 
        geosx::populateMaps                           0.005562      0.005562      0.005562  0.003956 
        geosx::resizeFaceToNodeMap                    0.017199      0.017199      0.017199  0.012234 
        geosx::createFacesByLowestNode                0.024956      0.024956      0.024956  0.017752 
      geosx::NodeManager::setElementMaps              0.024155      0.024155      0.024155  0.017182 
      geosx::ObjectManager~~ructGlobalToLocalMap      0.002366      0.002366      0.002366  0.001683
```

</details>

<details>
<summary>Here is the Caliper output on 8 ranks for Tutorial 5: `TimeHistoryOutput::initCollectorParallel` takes 120 seconds</summary>

```
Path                                             Min time/rank Max time/rank Avg time/rank Time %    
main                                                  0.052750      0.060925      0.058130  0.036352 
  geosx::EventManager::run                            1.114947      1.269002      1.154730  0.722119 
    geosx::PackCollection::collect                    0.000597      0.001054      0.000764  0.000478 
    geosx::SolverBase::execute                        0.000210      0.000964      0.000318  0.000199 
      geosx::ReservoirSolverBase::solverStep          0.178178      0.191908      0.184036  0.115088 
        geosx::SolverBase::nonlinearImplicitStep      1.000607      1.832680      1.304150  0.815560 
          geosx::Composition~~eFlow::updateState      0.012843      0.025186      0.018687  0.011686 
            geosx::Compositio~~datePhaseMobility      0.009427      0.011991      0.010823  0.006768 
            geosx::Compositio~~pdateRelPermModel      0.005475      0.007057      0.006548  0.004095 
            geosx::Compositio~~:updateSolidModel      0.002274      0.002818      0.002513  0.001572 
            geosx::Compositio~~aseVolumeFraction      0.007587      0.009144      0.008539  0.005340 
            geosx::Compositio~~:updateFluidModel      5.140704      5.949121      5.411772  3.384294 
            geosx::Compositio~~ComponentFraction      0.003634      0.004177      0.003859  0.002413 
          geosx::Communicati~~:synchronizeUnpack      0.006655      0.051014      0.032532  0.020344 
            geosx::NeighborCo~~packBufferForSync      0.017115      0.038503      0.027664  0.017300 
          geosx::Communicati~~ronizePackSendRecv      0.023106      0.795215      0.425269  0.265945 
            geosx::NeighborCo~~CommBufferForSync      0.022574      0.054503      0.038546  0.024105 
          geosx::Communicati~~ePackSendRecvSizes      0.011145      0.015694      0.013019  0.008142 
            geosx::NeighborCo~~ckCommSizeForSync      0.018229      0.041416      0.030121  0.018836 
          geosx::Composition~~heckSystemSolution      0.018876      0.018927      0.018907  0.011823 
          geosx::Composition~~gForSystemSolution      0.024364      0.024516      0.024460  0.015296 
          geosx::Composition~~gForSystemSolution      0.022688      0.025761      0.024279  0.015183 
          geosx::ReservoirSo~~rBase::solveSystem      0.003341      0.003815      0.003632  0.002272 
            geosx::SolverBase::solveSystem           12.074317     12.077975     12.076404  7.552074 
          geosx::Composition~~culateResidualNorm      0.018168      0.019838      0.019612  0.012265 
          geosx::Composition~~BoundaryConditions      0.001902      0.002414      0.002128  0.001330 
            geosx::FieldSpeci~~ionManager::apply      0.001096      0.001278      0.001170  0.000731 
          geosx::Composition~~mPressureRelations      0.020679      0.023996      0.022248  0.013913 
          geosx::Composition~~VolumeBalanceTerms      0.012873      0.014761      0.013616  0.008515 
          geosx::Composition~~:assembleFluxTerms      0.018376      0.022191      0.019965  0.012485 
          geosx::Composition~~tePerforationRates      0.049058      0.056306      0.051393  0.032139 
          geosx::Composition~~haseVolumeFraction      0.027925      0.034034      0.029622  0.018524 
          geosx::Composition~~::updateFluidModel      0.058520      0.107373      0.078727  0.049233 
          geosx::Composition~~eComponentFraction      0.022135      0.027069      0.023553  0.014729 
          geosx::Composition~~ow::assembleSystem      0.001987      0.002643      0.002206  0.001380 
            geosx::Compositio~~olumeBalanceTerms      0.007338      0.009120      0.008380  0.005241 
            geosx::Compositio~~assembleFluxTerms      0.253272      0.312935      0.281905  0.176292 
            geosx::Compositio~~AccumulationTerms      0.023443      0.036277      0.027004  0.016887 
        geosx::Compositiona~~utePerforationRates      0.004435      0.005447      0.004714  0.002948 
        geosx::Compositiona~~PhaseVolumeFraction      0.002536      0.004218      0.002900  0.001813 
        geosx::Compositiona~~l::updateFluidModel      0.005764      0.010791      0.007837  0.004901 
        geosx::Compositiona~~teComponentFraction      0.002116      0.002661      0.002299  0.001438 
        geosx::Compositiona~~ll::initializeWells      0.003790      0.009179      0.006970  0.004359 
          geosx::Composition~~tePerforationRates      0.000154      0.000188      0.000168  0.000105 
          geosx::Composition~~haseVolumeFraction      0.000064      0.000102      0.000082  0.000051 
          geosx::Composition~~::updateFluidModel      0.000128      0.000260      0.000187  0.000117 
          geosx::Composition~~eComponentFraction      0.000078      0.000128      0.000094  0.000059 
        geosx::Compositiona~~seFlow::updateState      0.003006      0.005988      0.004660  0.002914 
          geosx::Composition~~pdatePhaseMobility      0.002028      0.002604      0.002335  0.001460 
          geosx::Composition~~updateRelPermModel      0.001180      0.001440      0.001333  0.000834 
          geosx::Composition~~::updateSolidModel      0.000401      0.000542      0.000448  0.000280 
          geosx::Composition~~haseVolumeFraction      0.001657      0.002099      0.001928  0.001206 
          geosx::Composition~~::updateFluidModel      1.173678      1.387933      1.246159  0.779296 
          geosx::Composition~~eComponentFraction      0.000573      0.000710      0.000650  0.000406 
        geosx::ReservoirSolverBase::setupSystem       0.369140      0.421884      0.402024  0.251409 
          geosx::Composition~~ingSparsityPattern      0.072216      0.073820      0.072821  0.045539 
          geosx::Communicati~~:synchronizeUnpack      0.001255      0.013760      0.006113  0.003823 
            geosx::NeighborCo~~packBufferForSync      0.003661      0.008732      0.006190  0.003871 
          geosx::Communicati~~ronizePackSendRecv      0.003841      0.005404      0.004770  0.002983 
            geosx::NeighborCo~~CommBufferForSync      0.005461      0.013008      0.009340  0.005841 
          geosx::Communicati~~ePackSendRecvSizes      0.003299      0.004763      0.003862  0.002415 
            geosx::NeighborCo~~ckCommSizeForSync      0.005400      0.012334      0.008996  0.005626 
    geosx::TimeHistoryOutput::execute                 0.000019     60.222050     11.298333  7.065501 
  geosx::ProblemManager::problemSetup                 0.424783      0.453186      0.434049  0.271436 
    geosx::CompositionalM~~onditionsPreSubGroups      0.002518      0.002763      0.002634  0.001647 
      geosx::Compositional~~initializeFluidState      0.000199      0.000283      0.000242  0.000151 
        geosx::Compositiona~~updatePhaseMobility      0.000063      0.000081      0.000074  0.000046 
        geosx::Compositiona~~:updateRelPermModel      0.000044      0.000054      0.000047  0.000030 
        geosx::Compositiona~~w::updateSolidModel      0.000023      0.000028      0.000026  0.000016 
        geosx::Compositiona~~PhaseVolumeFraction      0.000066      0.000081      0.000072  0.000045 
        geosx::Compositiona~~w::updateFluidModel      0.033350      0.039863      0.035190  0.022006 
      geosx::Communication~~s::synchronizeUnpack      0.000017      0.000338      0.000239  0.000150 
        geosx::NeighborComm~~unpackBufferForSync      0.000048      0.000100      0.000073  0.000045 
      geosx::Communication~~chronizePackSendRecv      0.000124      0.001277      0.000801  0.000501 
        geosx::NeighborComm~~ckCommBufferForSync      0.000075      0.000193      0.000126  0.000079 
      geosx::Communication~~izePackSendRecvSizes      0.000054      0.000087      0.000075  0.000047 
        geosx::NeighborComm~~packCommSizeForSync      0.000074      0.000144      0.000111  0.000070 
    geosx::FluxApproximat~~onditionsPreSubGroups      0.007581      0.008909      0.008015  0.005012 
      geosx::FieldSpecificationManager::apply         0.000005      0.000007      0.000006  0.000004 
    geosx::TimeHistoryOut~~initCollectorParallel    120.107209    120.107329    120.107262 75.110018 
    geosx::FieldSpecificationManager::apply           0.000326      0.000537      0.000402  0.000252 
    geosx::ProblemManager::generateMesh               4.503567      4.534612      4.523300  2.828681 
      geosx::DomainPartiti~~:setupCommunications      0.012232      0.012331      0.012277  0.007678 
        geosx::FaceManager::sortAllFaceNodes          0.001304      0.001706      0.001502  0.000939 
        geosx::CommunicationTools::findGhosts         0.004075      0.086102      0.049837  0.031166 
          geosx::ObjectManag~~ase::fixUpDownMaps      0.002295      0.004293      0.003277  0.002049 
          geosx::NeighborCom~~ndRebuildSyncLists      0.000304      0.000630      0.000469  0.000293 
          geosx::NeighborCom~~reAndSendSyncLists      0.000354      0.000496      0.000440  0.000275 
          geosx::NeighborCom~~ator::unpackGhosts      0.034224      0.065791      0.047897  0.029953 
            "Unpack FixedToManyElementRelation"       0.000837      0.001766      0.001208  0.000756 
            "Unpack OrderedVa~~yElementRelation"      0.001631      0.003548      0.002404  0.001504 
            geosx::ObjectMana~~:unpackGlobalMaps      0.003568      0.006479      0.004849  0.003032 
          geosx::NeighborCom~~epareAndSendGhosts      0.039693      0.085183      0.059902  0.037460 
        geosx::Communicatio~~tionBoundaryObjects      0.001559      0.002263      0.001864  0.001166 
        geosx::Communicatio~~assignGlobalIndices      0.020546      0.021236      0.020897  0.013068 
          geosx::EdgeManager~~GlobalIndexNumbers      0.000155      0.000396      0.000232  0.000145 
          geosx::ObjectManag~~ctGlobalToLocalMap      0.001235      0.001365      0.001290  0.000807 
          geosx::FaceManager~~GlobalIndexNumbers      0.000336      0.000362      0.000352  0.000220 
      geosx::CellElementRe~~::generateAggregates      0.000003      0.000004      0.000004  0.000002 
      geosx::DomainPartition::generateSets            0.000804      0.000878      0.000839  0.000525 
      geosx::NodeManager::setEdgeMaps                 0.000627      0.000784      0.000695  0.000435 
      geosx::EdgeManager::buildEdges                  0.000295      0.000352      0.000321  0.000201 
        geosx::populateMaps                           0.000315      0.000388      0.000344  0.000215 
        geosx::resizeEdgeToFaceMap                    0.000270      0.000305      0.000287  0.000179 
        geosx::createEdgesByLowestNode                0.001561      0.002699      0.002292  0.001433 
      geosx::NodeManager::setFaceMaps                 0.000748      0.000872      0.000816  0.000510 
      geosx::FaceManager::buildFaces                  0.001522      0.001968      0.001708  0.001068 
        geosx::populateMaps                           0.001620      0.002200      0.001937  0.001211 
        geosx::resizeFaceToNodeMap                    0.001251      0.001546      0.001409  0.000881 
        geosx::createFacesByLowestNode                0.002487      0.003173      0.002807  0.001755 
      geosx::NodeManager::setElementMaps              0.001029      0.009304      0.003469  0.002170 
      geosx::ObjectManager~~ructGlobalToLocalMap      0.000523      0.000693      0.000609  0.000381
```

</details>

**To Reproduce**
1. download GEOSXDATA next to GEOSX
2. `git checkout feature/hamon/issue1069`
3. `git submodule update`
4. `make`
5. `srun -n 8 -p pdebug ~/geosx/GEOSX/build-quartz-clang@10.0.0-release/bin/geosx --input ~/geosx/GEOSX/src/coreComponents/physicsSolvers/fluidFlow/benchmarks/Egg/dead_oil_egg.xml -t runtime-report`

**Platform:**
- Machine: LLNL/Quartz   
- Compiler: `clang@10.0.0-release`
- GEOSX Version: `feature/hamon/issue1069`

**Additional context**
The problem is also present in `develop`, but is easier to reproduce on `feature/hamon/issue1069` because this branch solves an issue related to the PAMELA mesh importer (on `develop` tutorials 4 and 5 cannot be run in parallel).

### LINKED ISSUE #1356: [Bug] History collection give out of bound error with EmbeddedSurfaceSubRegion.
**Describe the bug**
Out of bound error in the pack collection when running cases with `EmbeddedSurfaceSubRegion`.

**To Reproduce**
Just try to run Tutorial 10 with a debug build.

### PR DESCRIPTION
**Pull request by wrtobin**
- [x] Fix #1356 
- [x] Fix #1309 
- [x] Resolve #1203
- [x] Collect data from arrays with an index set that can change size on any MPI rank during execution
- [x] Account for the changing sizes in buffered collected data when writing to file
   - Using the minimum index count from a rank involved in the writing works. Any larger and the HDF5 mpio routines error. Minimally this means doing writes with chunk size 1, since any ranks with 0 indices are excluded from the subcomm used to write a specific history 'row'. Efficiency of this approach is questionable, but this is the largest the chunk can reliably be.
- [x] Unit testing for (1) expanding and contracting data collection/output from the same process (2) repeated file writing with (1)
- [x] Allow collection of anything in the data repository (that is able to be collected). 
   - Since the dynamic collection changes the extent of the serialized portion of the time history 'row' that each MPI rank writes, we should also be able to use this to collect indexing data as well in order to help track specific items in a time history over the course of the simulation.

### CODE REVIEW

**Comment by castelletto1** [comment]
Hi @wrtobin, are you planning on taking care of #1203 within this PR?

**Comment by wrtobin** [comment]
@castelletto1 
I haven't added that yet, but it should be doable. 

This PR DOES include the ability to collect anything in the `dataRepository` (that is packable), which includes objects that aren't necessarily associated with the mesh (linear algebra package information, etc). So I'll have to add some internal logical to only add the coordinate information when collecting from mesh objects.

**Comment by wrtobin** [comment]
This requires a rebaseline as the tests deriving from sedov_base.xml will restart fail due to schema changes.

File: src/coreComponents/fileIO/timeHistory/PackCollection.cpp [hunk 1]
```diff
@@ -8,143 +8,211 @@ PackCollection::PackCollection ( string const & name, Group * parent )
...
+void PackCollection::initializePostSubGroups( )
 {
-  localIndex numSets = m_setNames.size( );
-  m_collectionCount = numSets == 0 ? 1 : numSets;
-  DomainPartition & domain = this->getGroupByPath< DomainPartition >( "/Problem/domain" );
-  updateSetsIndices( domain );
-  HistoryCollection::initializePostSubGroups();
+  if( !m_initialized )
+  {
+    DomainPartition & domain = this->getGroupByPath< DomainPartition >( "/Problem/domain" );
```
Comment (corbett5) [inline src/coreComponents/fileIO/timeHistory/PackCollection.cpp:38]: @rrsettgast is this preferred over `getGlobalState().problemManager().domain()`?

Comment (wrtobin) [reply src/coreComponents/fileIO/timeHistory/PackCollection.cpp:38]: I would think to prefer `getGlobalState().problemManager().domain()`, which is what I was using originally, this came in via a merge and I left it.

Comment (corbett5) [reply src/coreComponents/fileIO/timeHistory/PackCollection.cpp:38]: It might be the way it is to avoid dependencies.

File: src/coreComponents/physicsSolvers/solidMechanics/benchmarks/Sneddon-Validation.xml [hunk 2]
```diff
@@ -187,14 +179,7 @@
...
-      fieldName="displacementJump"
-      minSetSize="120"/>
-      
-    <PackCollection
-      name="cellCentersCollection"
-      objectPath="ElementRegions/Fracture/embeddedSurfaceSubRegion"
-      fieldName="elementCenter"
-      minSetSize="120"/>      
+      fieldName="displacementJump" />
   </Tasks>
```
Comment (CusiniM) [inline src/coreComponents/physicsSolvers/solidMechanics/benchmarks/Sneddon-Validation.xml:183]: no need for a min set size coz now the collection just gets resized every time the field changes size?

**Review by CusiniM — APPROVED** [review]
This is great! I would add an integrated test in which some non mesh objects are collected (e.g., nonlinear and linear iterations) so that we have a working example in there.

File: src/coreComponents/physicsSolvers/solidMechanics/benchmarks/Sneddon-Validation.xml (hunk 2 above)
Comment (wrtobin) [reply src/coreComponents/physicsSolvers/solidMechanics/benchmarks/Sneddon-Validation.xml:183]: Yes exactly. 

There can still be trailing 0s though since the HDF arrays aren't ragged / AoAs. Practically now we just expand the dataset as needed, which will add 0s to all previous 'rows', and we never contract the dataset: it will be sized to accommodate the largest set of collected data from the run.

Comment (corbett5) [reply src/coreComponents/physicsSolvers/solidMechanics/benchmarks/Sneddon-Validation.xml:183]: How hard would it be to write it out AoA style?

Comment (wrtobin) [reply src/coreComponents/physicsSolvers/solidMechanics/benchmarks/Sneddon-Validation.xml:183]: IIRC it will require defining a couple data types, one for the values extracted by a single index, and another variable-length type using the first type. Not sure how it plays in a dataspace with an unlimited dimension. 

The bigger unknown is dealing with the write in parallel w/ MPIO since HDF5 is a bit cumbersome in that respect... it might handle variable-length writes from processes transparently, or might require explicitly being told everything about the write (which is mostly the case right now).

Comment (CusiniM) [reply src/coreComponents/physicsSolvers/solidMechanics/benchmarks/Sneddon-Validation.xml:183]: I guess this will only happen if the collection has not been written to file yet. So, basically, if the field is resized in the same `packCollection` event before being written to file then all time-steps will have the field with the maximum size. But this should not happen if an output event occurs before the resizing. Am I wrong?

Comment (wrtobin) [reply src/coreComponents/physicsSolvers/solidMechanics/benchmarks/Sneddon-Validation.xml:183]: A size increase at any point results in the dimensions of the hdf dataspace being changed, so even rows already written to file will have 0s appended when the extent is changed.

Correlating the rows and the mesh object coordinates should in most cases allow the determination of which elements are padding elements and which are not.

File: src/coreComponents/dataRepository/HistoryDataSpec.hpp [hunk 3]
```diff
@@ -213,8 +213,13 @@ inline
...
 {
-  localIndex perIndexSize = arr[ 0 ].size( );
-  localIndex numIndices = ( sizeOverride >= 0 ? sizeOverride :  arr.size( ) / perIndexSize );
+  // Array dim > 1 so this should be valid
+  localIndex perIndexSize = arr.size( 1 );
+  localIndex numIndices = 0;
+  if( !arr.empty( ) )
+  {
+    numIndices = ( sizeOverride >= 0 ? sizeOverride :  arr.size( ) / perIndexSize );
+  }
```
Comment (rrsettgast) [inline src/coreComponents/dataRepository/HistoryDataSpec.hpp:222]:
```suggestion
  localIndex const perIndexSize = arr.size( 1 );
  localIndex const numIndices = sizeOverride >= 0 ? sizeOverride :  arr.size( ) / perIndexSize ) ;
```
if `arr.empty()` then `arr.size()` is zero...which is the desired value?

File: src/coreComponents/fieldSpecification/FieldSpecificationManager.hpp [hunk 4]
```diff
@@ -247,7 +247,7 @@ class FieldSpecificationManager : public dataRepository::Group
         if( ( isInitialCondition && fieldName=="" ) ||
             ( !isInitialCondition && time >= fs.getStartTime() && time < fs.getEndTime() && targetName==fieldName ) )
         {
-          dataRepository::Group * targetGroup = &domain.getMeshBody( 0 ).getMeshLevel( 0 );;
+          dataRepository::Group * targetGroup = &domain.getMeshBody( 0 ).getMeshLevel( 0 );
```
Comment (rrsettgast) [inline src/coreComponents/fieldSpecification/FieldSpecificationManager.hpp:250]:
```suggestion
          dataRepository::Group * const targetGroup = &domain.getMeshBody( 0 ).getMeshLevel( 0 );
```

File: src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp [hunk 5]
```diff
@@ -54,47 +54,67 @@ void TimeHistoryOutput::initCollectorParallel( DomainPartition & domain, History
...
+    // // invoke metadata collectors and write data from them during first-time init (not on restart),
+    // //  if there is actually any data to collect
+    // if( freshInit )
+    // {
+    //   metaCollector.execute( 0.0, 0.0, 0, 0, 0, domain );
+    //   for( localIndex ii = nonMetaCount; ii < ioCount; ++ii )
+    //   {
+    //     m_io[ii]->write( );
+    //   }
+    // }
```
Comment (rrsettgast) [inline src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp:103]:
```suggestion
```

File: src/coreComponents/fileIO/timeHistory/HistoryIO.hpp [hunk 6]
```diff
@@ -51,16 +51,17 @@ class BufferedHistoryIO
    */
   buffer_unit_type * getBufferHead( )
   {
-    resizeBuffer();
+    resizeBuffer( );
     m_bufferedCount++;
-    return m_bufferHead;
+    buffer_unit_type * currentBufferHead = m_bufferHead;
```
Comment (rrsettgast) [inline src/coreComponents/fileIO/timeHistory/HistoryIO.hpp:56]:
```suggestion
    buffer_unit_type * const currentBufferHead = m_bufferHead;
```

File: src/coreComponents/fileIO/timeHistory/PackCollection.cpp (hunk 1 above)
Comment (rrsettgast) [reply src/coreComponents/fileIO/timeHistory/PackCollection.cpp:38]: We have to fix this still...I was avoiding calls to `getGlobalState()` due to dependency issues, but I hadn't provided an accessor for domain. It isn't pleasant as it stands.

File: src/coreComponents/fileIO/timeHistory/PackCollection.cpp [hunk 7]
```diff
@@ -8,143 +8,211 @@ PackCollection::PackCollection ( string const & name, Group * parent )
...
+    localIndex numSets = m_setNames.size( );
+    m_collectionCount = numSets == 0 ? 1 : numSets;
+    // determine whether we're collecting from a mesh object manager
+    Group const * targetObject = this->getTargetObject( domain, m_objectPath );
+    ObjectManagerBase const * objectManagerTarget = dynamic_cast< ObjectManagerBase const * >( targetObject );
```
Comment (rrsettgast) [inline src/coreComponents/fileIO/timeHistory/PackCollection.cpp:43]: I always do like to make sure pointers are const if you don't plan on incrementing them.
```suggestion
    Group const * const targetObject = this->getTargetObject( domain, m_objectPath );
    ObjectManagerBase const * const objectManagerTarget = dynamic_cast< ObjectManagerBase const * >( targetObject );
```

...also we should make a templated version of `getTargetObject` that attempts the cast for you.

**Review by rrsettgast — APPROVED** [review]
just some nitpick things

**Comment by castelletto1** [comment]
I tried the integrated test `PoroElasticTerzaghi_FIM.xml`. Inspecting the pressure history output I see:

Screen Shot 2021-06-18 at 5 32 18 PM

I understand the `pressure` dataset: each row gives the pressure at an output time level (as shown in the `pressure Time` dataset) for the cell collection. What is not clear to me is the `pressure elementCenter` dataset: I would expect in each row the cell 0-coordinates -- in this snapshot, 1- and 2-coordinates look the same -- at the desired output time level, but I can only see zero values. 

Note that all values in the `pressure` dataset are zero because the traction field specification has to be done differently. This has been fixed in #1401 . However, this should have no impact on the `pressure elementCenter` dataset.

**Comment by wrtobin** [comment]
@castelletto1 
I made a change to when the coordinates were collected at some point which removed an extra row from the output (in order to get direct correspondence between the "time index" in all output datasets). This would've only effected static index sets, i.e. those that don't change size between initialization and the first collection task execution, which is what I must've been testing with. 

The last commit should fix this bug, thanks for catching it.

**Review by castelletto1 — APPROVED** [review]

**Comment by wrtobin** [comment]
This should be ready to go in.

https://github.com/GEOSX/integratedTests/pull/139 needs to be merged in first to account for the XML changes to the baselines that use the time history functionality.
