### PR TITLE
Fixing a typo in the default executable group timestep request

### LINKED ISSUE #1163: [Bug] EventManager and huge timesteps
For a reservoir simulation, we may need to use a solver run with huge initial timesteps to establish hydrostatic and lithostatic equilibrium, and then write a restart to use as initial conditions for a regular timescale simulation.

@juliatcamargo was running into a problem where she wanted to take `1e12 s` timesteps.   We found that for events that do not specify a `forceDt`, the EventManager always tried to take smaller timesteps than expected.  For example, having
```
   <SoloEvent
     name="restarts"
     targetTime="1.0e12"
     target="/Outputs/restartOutput"/>
```
would lead to the following behavior:
```
Running simulation
Time: 0s, dt:2.14748e+09s, Cycle: 0
     Event: 0 (outputs0), dt_request=1e+12, forecast=465
     Event: 1 (restarts), dt_request=2.14748e+09, forecast=465
Time: 2.14748e+09s, dt:9.97853e+11s, Cycle: 1
     Event: 0 (outputs0), dt_request=9.97853e+11, forecast=1
     Event: 1 (restarts), dt_request=9.97853e+11, forecast=1
Time: 1e+12s, dt:2.5e+06s, Cycle: 2
     Event: 0 (outputs0), dt_request=2.5e+06, forecast=0
     Event: 1 (restarts), dt_request=2.14748e+09, forecast=0
Rank 0: Writing out restart file at dontwork_restart_000000002/rank_0000000.hdf5
```
where we see that the restart event has a first `dt_request=2.1e9`.  Adding a `forceDt=1e12` fixes this behavior:
```
   <SoloEvent
     name="restarts"
     targetTime="1.0e12"
     forceDt="1.0e12"
     target="/Outputs/restartOutput"/>
```
```
Running simulation
Time: 0s, dt:1e+12s, Cycle: 0
     Event: 0 (outputs0), dt_request=1e+12, forecast=1
     Event: 1 (restarts), dt_request=1e+12, forecast=1
Time: 1e+12s, dt:2.5e+06s, Cycle: 1
     Event: 0 (outputs0), dt_request=2.5e+06, forecast=0
     Event: 1 (restarts), dt_request=1e+12, forecast=0
Rank 0: Writing out restart file at dontwork_restart_000000001/rank_0000000.hdf5
```
Trying to diagnose what is going on, I noticed in a few places in the EventManager we have lines like:
```
setForecast( static_cast< integer >(std::min( forecast, 1e9 )) );
```
where I am guessing `1e9` was meant to be a huge number.  Could this be the source of the issue?  

We can run the simulation fine with `forceDt`, but the behavior was a bit unexpected (particularly for a SoloEvent where we don't really think about timestep increments).  Any suggestions?

### PR DESCRIPTION
**Pull request by cssherman**
I'm suspicious about allowing the maximum double size for the default timestep request, so I'm setting it to 1/10th of max.

resolves #1163

### CODE REVIEW

**Review by joshua-white — APPROVED** [review]
Perfect, thanks!

**Review by klevzoff — APPROVED** [review]

File: src/coreComponents/dataRepository/ExecutableGroup.hpp [hunk 1]
```diff
@@ -90,7 +90,7 @@ class ExecutableGroup : public dataRepository::Group
   virtual real64 GetTimestepRequest( real64 const time )
   {
     GEOSX_UNUSED_VAR( time );
-    return std::numeric_limits< integer >::max();
+    return 0.1 * std::numeric_limits< real64 >::max();
```
Comment (rrsettgast) [inline src/coreComponents/dataRepository/ExecutableGroup.hpp:93]: I would say that 1e99 is sufficient

Comment (rrsettgast) [reply src/coreComponents/dataRepository/ExecutableGroup.hpp:93]: Actually I would say that `1e99` is preferred.

Comment (cssherman) [reply src/coreComponents/dataRepository/ExecutableGroup.hpp]: Sounds good, it's changed to 1e99 now

**Review by rrsettgast — APPROVED** [review]

File: src/coreComponents/dataRepository/ExecutableGroup.hpp (hunk 1 above)
Comment (rrsettgast) [reply src/coreComponents/dataRepository/ExecutableGroup.hpp]: Great. Thanks for the quick work.
