### PR TITLE
Fix parallel VTK output for wells

### LINKED ISSUE #1018: VTK output error
**Describe the bug**
I got this error running hi24l case using 64 cores on Quartz. This occurs at 1.6e6 seconds. The previous 15 vtk output writes seem fine.

Received signal 8: Floating point exception
Floating point exception:

** StackTrace of 24 frames **
Frame 1: LvArray::stackTraceHandler(int, bool)
Frame 2: 
Frame 3: 
Frame 4: vtkDataArray::ComputeVectorRange(double*)
Frame 5: vtkDataArray::ComputeRange(double*, int)
Frame 6: vtkXMLWriter::WriteArrayInline(vtkAbstractArray*, vtkIndent, char const*, int)
Frame 7: vtkXMLWriter::WritePointsInline(vtkPoints*, vtkIndent)
Frame 8: vtkXMLUnstructuredDataWriter::WriteInlinePiece(vtkIndent)
Frame 9: vtkXMLUnstructuredGridWriter::WriteInlinePiece(vtkIndent)
Frame 10: vtkXMLUnstructuredDataWriter::WriteInlineMode(vtkIndent)
Frame 11: vtkXMLUnstructuredDataWriter::WriteAPiece()
Frame 12: vtkXMLUnstructuredDataWriter::ProcessRequest(vtkInformation*, vtkInformationVector**, vtkInformationVector*)
Frame 13: vtkExecutive::CallAlgorithm(vtkInformation*, int, vtkInformationVector**, vtkInformationVector*)
Frame 14: vtkDemandDrivenPipeline::ExecuteData(vtkInformation*, vtkInformationVector**, vtkInformationVector*)
Frame 15: vtkCompositeDataPipeline::ExecuteData(vtkInformation*, vtkInformationVector**, vtkInformationVector*)
Frame 16: vtkDemandDrivenPipeline::ProcessRequest(vtkInformation*, vtkInformationVector**, vtkInformationVector*)
Frame 17: vtkStreamingDemandDrivenPipeline::ProcessRequest(vtkInformation*, vtkInformationVector**, vtkInformationVector*)
Frame 18: vtkDemandDrivenPipeline::UpdateData(int)
Frame 19: vtkStreamingDemandDrivenPipeline::Update(int, vtkInformationVector*)
Frame 20: vtkXMLWriter::Write()
Frame 21: geosx::vtk::VTKPolyDataWriterInterface::WriteUnstructuredGrid(vtkSmartPointer<vtkUnstructuredGrid>, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
Frame 22: geosx::vtk::VTKPolyDataWriterInterface::WriteWellElementRegions(double, geosx::ElementRegionManager const&, geosx::NodeManager const&) const
Frame 23: geosx::vtk::VTKPolyDataWriterInterface::Write(double, int, geosx::DomainPartition const&)
Frame 24: geosx::EventBase::Execute(double, double, int, int, double, geosx::dataRepository::Group*)
=====

### PR DESCRIPTION
**Pull request by francoishamon**
The PR fixes a crash in parallel simulations with wells that is occurring when a given rank does not have a well. In that case, the `WellElementSubRegion` on this rank has a size equal to zero, but we were specifying a number of points equal to one. This PR sets the number of points to zero is the sub-region size is zero, and to `esr.size()+1` otherwise.

This fixes this crash for the HI24L case that exhibited this problem.

Resolves #1018.

### CODE REVIEW

**Review by AntoineMazuyer — APPROVED** [review]
That was that ! Thanks !

File: src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp [hunk 1]
```diff
@@ -114,10 +114,11 @@ std::pair< vtkSmartPointer< vtkPoints >, vtkSmartPointer< vtkCellArray > >VTKPol
                                                                                                                NodeManager const & nodeManager ) const
 {
   vtkSmartPointer< vtkPoints > points = vtkPoints::New();
-  points->SetNumberOfPoints( esr.size() + 1 );
+  localIndex const numPoints = esr.size() > 0 ? esr.size() + 1 : 0;
```
Comment (TotoGaz) [inline src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp:117]: It's `0` when you have nothing and it's `esr.size() + 1` because the number of points is equal of the number of elements (which are segments: 2 nodes) + 1? Is that it?

Maybe a small in-line comment?

Comment (francoishamon) [reply src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp:123]: Thanks for looking at the PR. Yes, that is it. I added some comments at the top of this function to clarify the structure of the `WellElementSubRegion`, and why we need to set `numPoints` to zero when `esr.size()` is zero.

**Comment by francoishamon** [comment]
@TotoGaz @rrsettgast I think this PR is ready to be merged if you are good with the changes.

**Review by TotoGaz — APPROVED** [review]
