### PR TITLE
Fix compilation warning/error with clang

### LINKED ISSUE #2279: Compilation warning/error with clang
**Describe the bug**

1. : 

```
In file included from /GEOSX/src/coreComponents/constitutive/fluid/BlackOilFluid.cpp:15:
/GEOSX/src/coreComponents/constitutive/fluid/BlackOilFluid.hpp:1071:40: error: argument 'dRs_dComp' of type 'const geosx::real64[2]' (aka 'const double[2]') with mismatched bound [-Werror,-Warray-parameter]
                          real64 const dRs_dComp[HNC_BO],
                                       ^
/GEOSX/src/coreComponents/constitutive/fluid/BlackOilFluid.hpp:293:47: note: previously declared as 'const geosx::real64[]' (aka 'const double[]') here
                                 real64 const dRs_dComp[],
                                              ^
/GEOSX/src/coreComponents/constitutive/fluid/BlackOilFluid.hpp:1074:40: error: argument 'dBo_dComp' of type 'const geosx::real64[2]' (aka 'const double[2]') with mismatched bound [-Werror,-Warray-parameter]
                          real64 const dBo_dComp[HNC_BO],
                                       ^
/GEOSX/src/coreComponents/constitutive/fluid/BlackOilFluid.hpp:296:47: note: previously declared as 'const geosx::real64[]' (aka 'const double[]') here
                                 real64 const dBo_dComp[],

```

2. I didn't copy the error msg but clang complains also with this unused counter  

**To Reproduce**
Compile using:
```
➜  ~ clang --version
clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

```

**Expected behavior**
Compilation should proceed...

**Screenshots**
n.a.

**Platform (please complete the following information):**
- Machine [personal] 
- Compiler: [clang 15.0.7]
- GEOSX Version [develop branch]

**Additional context**
n.a.

### PR DESCRIPTION
**Pull request by untereiner**
Resolves #2279

### CODE REVIEW

File: src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp [hunk 1]
```diff
@@ -505,15 +505,15 @@ TEST_F( EzrokhiBrineViscosityTest, brineViscosityValuesAndDeriv )
...
+  // integer counter = 0;
   for( integer iComp = 0; iComp < 3; ++iComp )
   {
     for( integer iPres = 0; iPres < 3; ++iPres )
     {
       for( integer iTemp = 0; iTemp < 3; ++iTemp )
       {
         testNumericalDerivatives( pvtFunctionWrapper, P[iPres], TC[iTemp], comp, true, eps, relTol );
-        counter++;
+        // counter++;
```
Comment (TotoGaz) [inline src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp:516]:
```suggestion
```

File: src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp [hunk 2]
```diff
@@ -653,15 +653,15 @@ TEST_F( PhillipsBrineDensityTest, brineCO2DensityMolarValuesAndDeriv )
 
   PhillipsBrineDensity::KernelWrapper pvtFunctionWrapper = pvtFunction->createKernelWrapper();
 
-  integer counter = 0;
+  // integer counter = 0;
```
Comment (TotoGaz) [inline src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp:656]:
```suggestion
```

File: src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp [hunk 3]
```diff
@@ -704,15 +704,15 @@ TEST_F( EzrokhiBrineDensityTest, brineCO2DensityMassValuesAndDeriv )
 
   EzrokhiBrineDensity::KernelWrapper pvtFunctionWrapper = pvtFunction->createKernelWrapper();
 
-  integer counter = 0;
+  // integer counter = 0;
```
Comment (TotoGaz) [inline src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp:707]:
```suggestion
```

File: src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp [hunk 4]
```diff
@@ -704,15 +704,15 @@ TEST_F( EzrokhiBrineDensityTest, brineCO2DensityMassValuesAndDeriv )
...
   for( integer iComp = 0; iComp < 3; ++iComp )
   {
     for( integer iPres = 0; iPres < 3; ++iPres )
     {
       for( integer iTemp = 0; iTemp < 3; ++iTemp )
       {
         testNumericalDerivatives( pvtFunctionWrapper, P[iPres], TC[iTemp], comp, true, eps, relTol );
-        counter++;
+        // counter++;
```
Comment (TotoGaz) [inline src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp:715]:
```suggestion
```

File: src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp [hunk 5]
```diff
@@ -735,15 +735,15 @@ TEST_F( EzrokhiBrineDensityTest, brineCO2DensityMolarValuesAndDeriv )
 
   EzrokhiBrineDensity::KernelWrapper pvtFunctionWrapper = pvtFunction->createKernelWrapper();
 
-  integer counter = 0;
+  // integer counter = 0;
```
Comment (TotoGaz) [inline src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp:738]:
```suggestion
```

File: src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp [hunk 6]
```diff
@@ -735,15 +735,15 @@ TEST_F( EzrokhiBrineDensityTest, brineCO2DensityMolarValuesAndDeriv )
...
   for( integer iComp = 0; iComp < 3; ++iComp )
   {
     for( integer iPres = 0; iPres < 3; ++iPres )
     {
       for( integer iTemp = 0; iTemp < 3; ++iTemp )
       {
         testNumericalDerivatives( pvtFunctionWrapper, P[iPres], TC[iTemp], comp, false, eps, relTol );
-        counter++;
+        // counter++;
```
Comment (TotoGaz) [inline src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp:746]:
```suggestion
```

**Review by TotoGaz — COMMENTED** [review]
Remove the commented lines and I think it's OK.

**Review by TotoGaz — APPROVED** [review]
