### PR TITLE
Bugfix/castelletto1/issue 1708

### LINKED ISSUE #1708: testLinearAlgebra_ExternalSolvers fails on travis gcc 9
On `travis-ci`, target `ubuntu 20.04 gcc 9 release`, the unit test `testLinearAlgebra_ExternalSolvers` segfaults:

```
        Start  98: testLinearAlgebra_ExternalSolvers
98: Test command: /usr/bin/mpirun "-n" "2" "--allow-run-as-root" "--oversubscribe" "/tmp/build/tests/testExternalSolvers" "-x" "2"
98: Test timeout computed to be: 1500
98: [==========] Running 8 tests from 2 test suites.
98: [==========] Running 8 tests from 2 test suites.
98: [----------] Global test environment set-up.
98: [----------] 5 tests from Trilinos/SolverTestLaplace2D/0, where TypeParam = geosx::TrilinosInterface
98: [----------] Global test environment set-up.
98: [----------] 5 tests from Trilinos/SolverTestLaplace2D/0, where TypeParam = geosx::TrilinosInterface
98: [ RUN      ] Trilinos/SolverTestLaplace2D/0.DirectSerial
98: [ RUN      ] Trilinos/SolverTestLaplace2D/0.DirectSerial
98: [       OK ] Trilinos/SolverTestLaplace2D/0.DirectSerial (461 ms)
98: [ RUN      ] Trilinos/SolverTestLaplace2D/0.DirectParallel
98: [       OK ] Trilinos/SolverTestLaplace2D/0.DirectSerial (462 ms)
98: [ RUN      ] Trilinos/SolverTestLaplace2D/0.DirectParallel
98: [       OK ] Trilinos/SolverTestLaplace2D/0.DirectParallel (432 ms)
98: [ RUN      ] Trilinos/SolverTestLaplace2D/0.GMRES_ILU
98: [       OK ] Trilinos/SolverTestLaplace2D/0.DirectParallel (436 ms)
98: [ RUN      ] Trilinos/SolverTestLaplace2D/0.GMRES_ILU
98: [       OK ] Trilinos/SolverTestLaplace2D/0.GMRES_ILU (182 ms)
98: [ RUN      ] Trilinos/SolverTestLaplace2D/0.CG_SGS
98: [       OK ] Trilinos/SolverTestLaplace2D/0.GMRES_ILU (182 ms)
98: [ RUN      ] Trilinos/SolverTestLaplace2D/0.CG_SGS
98: [       OK ] Trilinos/SolverTestLaplace2D/0.CG_SGS (274 ms)
98: [ RUN      ] Trilinos/SolverTestLaplace2D/0.CG_AMG
98: [       OK ] Trilinos/SolverTestLaplace2D/0.CG_SGS (273 ms)
98: [ RUN      ] Trilinos/SolverTestLaplace2D/0.CG_AMG
98: [       OK ] Trilinos/SolverTestLaplace2D/0.CG_AMG (101 ms)
98: [----------] 5 tests from Trilinos/SolverTestLaplace2D/0 (1453 ms total)
98: 
98: [----------] 3 tests from Trilinos/SolverTestElasticity2D/0, where TypeParam = geosx::TrilinosInterface
98: [ RUN      ] Trilinos/SolverTestElasticity2D/0.DirectSerial
98: [       OK ] Trilinos/SolverTestLaplace2D/0.CG_AMG (102 ms)
98: [----------] 5 tests from Trilinos/SolverTestLaplace2D/0 (1456 ms total)
98: 
98: [----------] 3 tests from Trilinos/SolverTestElasticity2D/0, where TypeParam = geosx::TrilinosInterface
98: [ RUN      ] Trilinos/SolverTestElasticity2D/0.DirectSerial
98: Received signal 8: Floating point exception
98: Floating point exception:
98: 
98: ** StackTrace of 14 frames **
98: Frame 0: /lib/x86_64-linux-gnu/libc.so.6 
98: Frame 1: Epetra_MultiVector::Norm2(double*) const 
98: Frame 2: geosx::EpetraVector::norm2() const 
98: Frame 3: geosx::SuiteSparse<geosx::TrilinosInterface>::solve(geosx::EpetraVector const&, geosx::EpetraVector&) const 
98: Frame 4: SolverTestBase<geosx::TrilinosInterface>::test(geosx::LinearSolverParameters const&) 
98: Frame 5: gtest_suite_SolverTestElasticity2D_::DirectSerial<geosx::TrilinosInterface>::TestBody() 
98: Frame 6: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) 
98: Frame 7: testing::Test::Run() 
98: Frame 8: testing::TestInfo::Run() 
98: Frame 9: testing::TestSuite::Run() 
98: Frame 10: testing::internal::UnitTestImpl::RunAllTests() 
98: Frame 11: testing::UnitTest::Run() 
98: Frame 12: main 
98: Frame 13: __libc_start_main 
98: Frame 14: _start 
98: =====
98: 
98: --------------------------------------------------------------------------
98: MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
98: with errorcode 1.
98: 
98: NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
98: You may or may not see output from other processes, depending on
98: exactly when Open MPI kills them.
98: --------------------------------------------------------------------------
98: Received signal 15: Terminated
98: 
98: ** StackTrace of 20 frames **
98: Frame 0: /lib/x86_64-linux-gnu/libc.so.6 
98: Frame 1: __sched_yield 
98: Frame 2: ompi_request_default_wait 
98: Frame 3: ompi_coll_base_sendrecv_actual 
98: Frame 4: ompi_coll_base_allreduce_intra_recursivedoubling 
98: Frame 5: PMPI_Allreduce 
98: Frame 6: Epetra_MpiComm::SumAll(double*, double*, int) const 
98: Frame 7: Epetra_MultiVector::Norm2(double*) const 
98: Frame 8: geosx::EpetraVector::norm2() const 
98: Frame 9: geosx::SuiteSparse<geosx::TrilinosInterface>::solve(geosx::EpetraVector const&, geosx::EpetraVector&) const 
98: Frame 10: SolverTestBase<geosx::TrilinosInterface>::test(geosx::LinearSolverParameters const&) 
98: Frame 11: gtest_suite_SolverTestElasticity2D_::DirectSerial<geosx::TrilinosInterface>::TestBody() 
98: Frame 12: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) 
98: Frame 13: testing::Test::Run() 
98: Frame 14: testing::TestInfo::Run() 
98: Frame 15: testing::TestSuite::Run() 
98: Frame 16: testing::internal::UnitTestImpl::RunAllTests() 
98: Frame 17: testing::UnitTest::Run() 
98: Frame 18: main 
98: Frame 19: __libc_start_main 
98: Frame 20: _start 
98: =====
98: 
98: [b17f89f7426d:09779] 1 more process has sent help message help-mpi-api.txt / mpi-abort
98: [b17f89f7426d:09779] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
 98/149 Test  #98: testLinearAlgebra_ExternalSolvers ....................***Failed    5.59 sec
```

### PR DESCRIPTION
**Pull request by castelletto1**
Resolves #1708.

### CODE REVIEW

**Review by klevzoff — APPROVED** [review]

File: src/coreComponents/linearAlgebra/unitTests/testLinearAlgebraUtils.hpp [hunk 1]
```diff
@@ -426,6 +421,10 @@ void compute2DElasticityOperator( MPI_Comm const comm,
     globalIndex dofIndex[8];
     computeQuadElementDofIndices( iCell + iStart, nCellsX, dofIndex );
 
+    // Construct local stiffness matrix (same for all cells)
```
Comment (TotoGaz) [inline src/coreComponents/linearAlgebra/unitTests/testLinearAlgebraUtils.hpp:424]:
```suggestion
    // Construct local stiffness matrix (same for all cells).
    // This could be done out of the `forAll` loop,
    // but a strange behavior of `gcc 9` in `Release` doesn't copy `Ke` properly.
```

**Review by TotoGaz — COMMENTED** [review]
Thx @castelletto1 for figuring that out.

If the problem is that the lambda capure is not properly done, maybe could be change it for `Ke`? Like
```c++
  forAll< parallelDevicePolicy<> >( LvArray::integerConversion< localIndex >( iEnd - iStart ),
                                    [=, &Ke] GEOSX_DEVICE ( localIndex const iCell )
 ```
But I expect this to be incompatible with `GEOSX_DEVICE`, isn't it?

**Comment by castelletto1** [comment]
> But I expect this to be incompatible with GEOSX_DEVICE, isn't it? 

Yes

**Comment by castelletto1** [comment]
Following a suggestion by @klevzoff, I tried `stackArray2d` instead of c array for `Ke`. It turned out that `Ke` gets captured by value correctly using `gcc 9`. Hence, I moved the computation of `Ke` back outside the `forAll` loop.

**Comment by TotoGaz** [comment]
@castelletto1 We're going to merge this. Are you OK?
